### ISSUE TITLE
How to use it in angular project?

### ISSUE THREAD

**Issue by shubhamkes** [artf/codemirror-formatting#1]
Am using ui-codemirror directive.
if I use CodeMirror.fromTextArea() , i wont be able to use directive, and if using directive I wont be getting methods like autoFormatRange

**Comment by artf** [comment]
[ui-codemirror](https://github.com/angular-ui/ui-codemirror#codemirror-instance-direct-access) shows you how to get CodeMirror editor instance
```js
myAppModule.controller('MyController', [ '$scope', function($scope) {
  $scope.codemirrorLoaded = function(_editor){
    ...
    _editor.autoFormatRange(...);
  };
}]);
```
